Repository cilium/packer-ci-build, pull requests merged in 2018-02, with the labels that each got.

#21 Ubuntu: Fix issues with the DNS
  provision/ubuntu/install.sh
Labels: bug

#24 add patch to pre-build envoy with experimental_strict_action_env
  provision/envoy.sh
Labels: enhancement

#25 Fix envoy build
  Jenkinsfile
  provision/envoy.sh
  provision/golang.sh
  provision/registry.sh
Labels: bug, enhancement

#26 provision: switch python image tag to a slimmer one
  provision/envoy.sh
  provision/pull-images.sh
Labels: enhancement

#27 provision: update bazel to 0.10.1
  provision/env.bash
Labels: enhancement
