Repository cilium/packer-ci-build, pull requests merged in 2018-10, with the labels that each got.

#87 provision: add cfssl utility
  provision/ubuntu/install.sh
Labels: pending-review

#88 provision: update image tags
  provision/pull-images.sh
Labels: enhancement, pending-review

#39 Ubuntu-next: Add the kernel net-next in ubuntu base image
  Jenkinsfile-next
  Makefile
  cilium-ubuntu-next.json
  provision/ubuntu/install.sh
  provision/ubuntu/kernel-next.sh
Labels: enhancement

#97 provision: update image tags
  provision/pull-images.sh
Labels: enhancement, pending-review

#99 Added 1.3 docker image
  provision/pull-images.sh
Labels: pending-review
